### ISSUE TITLE
Đặc tả bằng sơ đồ UseCase

### ISSUE THREAD

**Issue by dream2216** [dream2216/ProjectSE_CNPM#10]
![Capture](https://user-images.githubusercontent.com/56868551/112727749-8b2eed80-8f56-11eb-9345-3f21227ad797.PNG)

**Comment by vohung-tu** [comment]
![Capture](https://user-images.githubusercontent.com/56868551/112727714-620e5d00-8f56-11eb-9afa-351e776c0713.PNG)
